AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  RUNLEVEL:
    Type: "String"
    Default: "DEBUG"
  GOOGLECLIENTID:
    Type: "String"
  GOOGLECLIENTSECRET:
    Type: "String"
  APISTAGE:
    Type: "String"
    Default: "test"
  FUNCTIONALIAS:
    Type: "String"
    Default: "test"
Resources:
  LambdaExecPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource:
              - !GetAtt SessionTable.Arn
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TrashSchedule"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TrashSchedule/index/signinId-index"
      PolicyName: !Sub "throwtrash-backend-policy-${AWS::Region}"
      Roles:
        - !Ref LambdaExecRole
    DeletionPolicy: Retain
  LambdaExecRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      RoleName: !Sub "throwtrash-backend-lambda-role-${AWS::Region}"
    DeletionPolicy: Retain
  SessionTable:
    Type: "AWS::Serverless::SimpleTable"
    Properties:
      PrimaryKey:
        Name: "id"
        Type: String
      TableName: ThrowTrashSession
    DeletionPolicy: Retain
  LambdaFunction:
    Type: "AWS::Serverless::Function"
    DeletionPolicy: Retain
    Properties:
      CodeUri: .
      FunctionName: ThrowTrashBackend
      Handler: index.handler
      Role: !GetAtt LambdaExecRole.Arn
      Runtime: nodejs12.x
      AutoPublishAlias: !Ref FUNCTIONALIAS
      Timeout: 30
      Environment:
        Variables:
          DB_REGION: !Sub "${AWS::Region}"
          RUNLEVEL: !Ref RUNLEVEL
          GOOGLE_CLIENT_ID: !Ref GOOGLECLIENTID
          GOOGLE_CLIENT_SECRET: !Ref GOOGLECLIENTSECRET
          GOOGLE_APPLICATION_CREDENTIALS: "/var/task/serviceAccountKey.json"
      Events:
        OAuthRequest:
          Type: Api
          Properties:
            Path: "/oauth_request"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.state:
                  Required: true
              - method.request.querystring.client_id:
                  Required: true
              - method.request.querystring.redirect_uri:
                  Required: true
              - method.request.querystring.platform:
                  Required: true
              - method.request.querystring.version:
                  Required: true
        OAuthSignin:
          Type: Api
          Properties:
            Path: "/google_signin"
            Method: "GET"
            RestApiId: !Ref Api
        SignIn:
          Type: Api
          Properties:
            Path: "/signin"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.service:
                  Required: true
              - 'method.request.querystring.access_token'
              - 'method.request.querystring.code'
              - 'method.request.querystring.state'
        SignOut:
          Type: Api
          Properties:
            Path: "/signout"
            Method: "GET"
            RestApiId: !Ref Api
        UserInfo:
          Type: Api
          Properties:
            Path: "/user_info"
            Method: "GET"
            RestApiId: !Ref Api
        Regist:
          Type: Api
          Properties:
            Path: "/regist"
            Method: "POST"
            RestApiId: !Ref Api
  Api:
    Type: "AWS::Serverless::Api"
    DeletionPolicy: Retain
    Properties:
      Name: "ThrowTrashBackendApi"
      StageName: !Ref APISTAGE
      Variables: 
        Alias: "development"
      Cors:
        AllowMethods: "'GET,POST'"
        AllowOrigin: "'https://accountlink.mythrowaway.net'"
        AllowHeaders: "'Content-Type'"
        AllowCredentials: true
