version: "2.1"
cjobs:
  test:
    docker:
      - image: circleci/node:10.1.0
    steps:
      - checkout
      - run:
          name: install
          command: npm install
          working_directory: server
      - run:
          name: backend test
          command: npm test
          working_directory: server
      - run:
          name: frontend test
          command: npm run test-front
          working_directory: server
  deploy:
    docker: 
      - image: kroniak/ssh-client:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${SSH_KEY_PRODUCTION}
            - ${SSH_KEY_STAGING}
      - run:
          name: set environment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "export HOST_NAME=${HOST_PRODUCTION}" >> $BASH_ENV
            else
              echo "export HOST_NAME=${HOST_STAGING}" >> $BASH_ENV
            fi
      - run:
          name: deployment
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan -H ${HOST_NAME} >> ~/.ssh/known_hosts
            ssh ${SSH_USER}@${HOST_NAME} 'hostname'
            ssh ${SSH_USER}@${HOST_NAME} "sudo docker run --rm -v ${PROJECT_DIRECTORY}:/git alpine/git fetch"
            ssh ${SSH_USER}@${HOST_NAME} "sudo docker run --rm -v ${PROJECT_DIRECTORY}:/git checkout ${CIRCLE_BRANCH}"
            ssh ${SSH_USER}@${HOST_NAME} "sudo docker-compose -f ${PROJECT_DIRECTORY}/docker/docker-compose.xml restart node"
    
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: aws-test
      - deploy:
          requires:
            - test
c