AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  SessionTableName:
    Type: "String"
    Default: "throwtrash-backend-session"
  AuthorizationTableName:
    Type: "String"
    Default: "throwtrash-backend-authorization"
  AccessTokenTableName:
    Type: "String"
    Default: "throwtrash-backend-accesstoken"
  RefreshTokenTableName:
    Type: "String"
    Default: "throwtrash-backend-refreshtoken"
  TrashScheduleTableName:
    Type: "String"
    Default: "TrashSchedule"
  SigninIdIndexName:
    Type: "String"
    Default: "signinId-index"
Resources:
  TrashScheduleTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      Tags:
        -
          Key: Group
          Value: throwtrash
        -
          Key: Purpose
          Value: WebBackend/MobileBackend/Skill
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "signinId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: !Ref SigninIdIndexName
          KeySchema:
            - 
              AttributeName: "signinId"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "description"
              - "id"
              - "signinService"
            ProjectionType: "INCLUDE"
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: !Ref TrashScheduleTableName
    DeletionPolicy: Retain
  SessionTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: HASH
      TableName: !Ref SessionTableName
      TimeToLiveSpecification:
        AttributeName: expire
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      Tags:
        -
          Key: Group
          Value: throwtrash
        -
          Key: Purpose
          Value: WebBackend/OAuthBackend
    DeletionPolicy: Retain
  AuthorizationTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "code"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "code"
          KeyType: HASH
      TableName: !Ref AuthorizationTableName
      TimeToLiveSpecification:
        AttributeName: expires_in
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      Tags:
        -
          Key: Group
          Value: throwtrash
        -
          Key: Purpose
          Value: OAuthBackend
    DeletionPolicy: Retain
  AccessTokenTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "access_token"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "access_token"
          KeyType: HASH
      TableName: !Ref AccessTokenTableName
      TimeToLiveSpecification:
        AttributeName: expires_in
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      Tags:
        -
          Key: Group
          Value: throwtrash
        -
          Key: Purpose
          Value: OAuthBackend
    DeletionPolicy: Retain
  RefreshTokenTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "refresh_token"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "refresh_token"
          KeyType: HASH
      TableName: !Ref RefreshTokenTableName
      TimeToLiveSpecification:
        AttributeName: expires_in
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      Tags:
        -
          Key: Group
          Value: throwtrash
        -
          Key: Purpose
          Value: OAuthBackend
    DeletionPolicy: Retain
Outputs:
  AuthorizationTable:
    Export:
      Name: !Sub "throwtrash-db-authorization"
    Value: !Ref AuthorizationTableName
  AccessTokenTable:
    Export:
      Name: !Sub "throwtrash-db-accesstoken"
    Value: !Ref AccessTokenTableName
  RefreshTokenTable:
    Export:
      Name: !Sub "throwtrash-db-refreshtoken"
    Value: !Ref RefreshTokenTableName
  SessionTable:
    Export:
      Name: !Sub "throwtrash-db-session"
    Value: !Ref SessionTableName
  TrashScheduleTable:
    Export:
      Name: !Sub "throwtrash-db-schedule"
    Value: !Ref TrashScheduleTableName
  SigninIdIndex:
    Export:
      Name: !Sub "throwtrash-db-schedule-signinIndex"
    Value: !Ref SigninIdIndexName
