AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  RunLevel:
    Type: "String"
    Default: "DEBUG"
  GoogleClientID:
    Type: "String"
  GoogleClientSecret:
    Type: "String"
  Stage:
    Type: "String"
    Default: "dev"
  AlexaClientID:
    Type: "String"
  AlexaClientSecret:
    Type: "String"
  AlexaUserClientID:
    Type: "String"
  AlexaUserSecret:
    Type: "String"
  GoogleUserClientID:
    Type: "String"
  GoogleUserSecret:
    Type: "String"
  AlexaSkillID:
    Type: "String"
  DBRegion:
    Type: "String"
Resources:
  LambdaExecPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource:
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  - Fn::ImportValue: throwtrash-db-schedule
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  - Fn::ImportValue: throwtrash-db-schedule
                  - "index"
                  - Fn::ImportValue: throwtrash-db-schedule-signinIndex
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  - Fn::ImportValue: throwtrash-db-accesstoken
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  - Fn::ImportValue: throwtrash-db-refreshtoken
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  - Fn::ImportValue: throwtrash-db-authorization
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  - Fn::ImportValue: throwtrash-db-session
              # - Fn::Join:
              #   - /
              #   - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
              #     - Fn::ImportValue: throwtrash-db-shared-schedule
              - Fn::Join:
                - /
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  #TODO: 東東リージョンのDB更新時にImportValueに置き換える
                  - "throwtrash-accountlink"
                - - Fn::Sub: arn:aws:dynamodb:${DBRegion}:${AWS::AccountId}:table
                  #TODO: 東東リージョンのDB更新時にImportValueに置き換える
                  - "throwtrash-shared-schedule"
      PolicyName: !Sub "throwtrash-backend-lambda-policy-${Stage}"
      Roles:
        - !Ref LambdaExecRole
    DeletionPolicy: Retain
  LambdaExecRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      RoleName: !Sub "throwtrash-backend-lambda-exec-role-${Stage}"
    DeletionPolicy: Retain
  FunctionLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      ContentUri: ../src/layer
      LayerName: !Sub "throwtrash-backend-layer-${Stage}"
      CompatibleRuntimes:
        - nodejs16.x
  LambdaFunction:
    Type: "AWS::Serverless::Function"
    DeletionPolicy: Retain
    Properties:
      CodeUri: ../src/backend-dist
      FunctionName: !Sub "throwtrash-backend-${Stage}"
      Handler: index.handler
      Role: !GetAtt  LambdaExecRole.Arn
      Runtime: nodejs16.x
      Timeout: 30
      Layers:
        - !Ref FunctionLayer
      Environment:
        Variables:
          DB_REGION: !Ref DBRegion
          RUNLEVEL: !Ref RunLevel
          GOOGLE_CLIENT_ID: !Ref GoogleClientID
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_APPLICATION_CREDENTIALS: "/var/task/serviceAccountKey.json"
          ALEXA_CLIENT_ID: !Ref AlexaClientID
          ALEXA_CLIENT_SECRET: !Ref AlexaClientSecret
          ALEXA_USER_CLIENT_ID: !Ref AlexaUserClientID
          ALEXA_USER_SECRET: !Ref AlexaUserSecret
          GOOGLE_USER_CLIENT_ID: !Ref GoogleUserClientID
          GOOGLE_USER_SECRET: !Ref GoogleUserSecret
          ALEXA_SKILL_ID: !Ref AlexaSkillID
      Tags:
        Group: throwtrash
        Purpose: WebBackend/OAuthBackend
      Events:
        OAuthRequest:
          Type: Api
          Properties:
            Path: "/oauth_request"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.state:
                  Required: true
              - method.request.querystring.client_id:
                  Required: true
              - method.request.querystring.redirect_uri:
                  Required: true
              - method.request.querystring.platform:
                  Required: true
        OAuthSignin:
          Type: Api
          Properties:
            Path: "/google_signin"
            Method: "GET"
            RestApiId: !Ref Api
        SignIn:
          Type: Api
          Properties:
            Path: "/signin"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.service:
                  Required: true
              - 'method.request.querystring.access_token'
              - 'method.request.querystring.code'
              - 'method.request.querystring.state'
        SignOut:
          Type: Api
          Properties:
            Path: "/signout"
            Method: "GET"
            RestApiId: !Ref Api
        UserInfo:
          Type: Api
          Properties:
            Path: "/user_info"
            Method: "GET"
            RestApiId: !Ref Api
        Regist:
          Type: Api
          Properties:
            Path: "/regist"
            Method: "POST"
            RestApiId: !Ref Api
        RequestAccessToken:
          Type: Api
          Properties:
            Path: "/request_accesstoken"
            Method: "POST"
            RestApiId: !Ref Api
        StartLink:
          Type: Api
          Properties:
            Path: "/start_link"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.platform:
                  Required: true
        ExchangeAmazonCode:
          Type: Api
          Properties:
            Path: "/enable_skill"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.state:
                  Required: true
              - method.request.querystring.code:
                  Required: true
              - method.request.querystring.scope:
                  Required: true
              - method.request.querystring.redirect_uri:
                  Required: true
        RequestAuthrozationCode:
          Type: Api
          Properties:
            Path: "/request_authorization_code"
            Method: "GET"
            RestApiId: !Ref Api
            Auth:
              ApiKeyRequired: true
            RequestParameters:
              - method.request.querystring.user_id:
                  Required: true
              - method.request.querystring.client_id:
                  Required: true
              - method.request.querystring.redirect_uri:
                  Required: true
  Api:
    Type: "AWS::Serverless::Api"
    DeletionPolicy: Retain
    Properties:
      Name: !Sub "throwtrash-backend-${Stage}"
      Tags:
        Group: throwtrash
        Purpose: WebBackend/OAuthBackend
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST'"
        AllowOrigin: "'https://accountlink.mythrowaway.net'"
        AllowHeaders: "'Content-Type'"
        AllowCredentials: true
      MethodSettings:
        -
          LoggingLevel: "INFO"
          HttpMethod: "*"
          ResourcePath: "/*"
          DataTraceEnabled: true
  LambdaVersion:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn