name: "Frontend Deploy"
description: "Deploy the frontend"
inputs:
  front-stage:
    description: "The frontend stage"
    required: true
  bucket:
    description: "The name of the S3 bucket"
    required: true
runs:
  using: composite
  steps:
    - name: S3 Sync
      shell: bash
      run: |
        aws s3 sync frontend/frontend-dist/${{ inputs.front-stage }} s3://${{ inputs.bucket }}/${{ inputs.front-stage }}