version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1.7.3
    ports:
      - '80:80'
      - '443:443'
    links:
      - node
    restart: always
    environment:
      STAGE: ${HTTP_STAGE}
      DOMAINS: '${HTTP_DOMAIN} -> http://node:${NODE_PORT}'
    volumes:
      - ./web/cert:/var/lib/https-portal
    dns: 8.8.8.8
  node:
    build: 
      context: ./app
    volumes: 
        - ../server:/src
    expose: 
        - 2000
    environment: 
        - NODE_OPTION=--port=${NODE_PORT} --level=${NODE_LEVEL} --mode=${NODE_MODE}
    dns: 8.8.8.8