version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1.7.3
    ports:
      - '80:80'
      - '443:443'
    links:
      - node
    restart: always
    environment:
      STAGE: 'production'
      DOMAINS: '${FQDN} -> http://node:2000'
    volumes:
      - ./web/cert:/var/lib/https-portal
    dns: 8.8.8.8
  node:
    build: 
      context: ./app
    volumes: 
        - ../server:/src
    expose: 
        - 2000
    environment: 
        - NODE_OPTION=--port 2000 
    dns: 8.8.8.8