#!/bin/bash

if [ "${CIRCLE_BRANCH}" = "deploy" ]; then
  # masterはマージコミットなどの場合なので一つ前と比較する
  DIFF_TARGET="HEAD^ HEAD"
else
  DIFF_TARGET="origin/master"
fi

# sed の -z オプションはGNU版Linuxのオプション
DIFF_FILES=(`git diff ${DIFF_TARGET} --name-only --relative=${1} | sed -z 's/\n/ /g'`)

if [ ${#DIFF_FILES[@]} -eq 0 ]; then
  exit 1
else
  exit 0
fi
