AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  ActivationTableName:
    Type: String
    Default: throwtrash-activation
  Stage:
    Type: String
    Default: "dev"
Resources:
  ActivationTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "code" 
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "code"
          KeyType: HASH
      TableName: !Ref ActivationTableName 
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      Tags:
        -
          Key: Group
          Value: throwtrash
        -
          Key: Purpose
          Value: MobileBackend
    DeletionPolicy: Retain
Outputs:
  ActivationTable:
    Export:
      Name: "throwtrash-db-activation"
    Value: !Ref ActivationTableName