AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  RunLevel:
    Type: "String"
    Default: "DEBUG"
  Stage:
    Type: "String"
    Default: "dev"
  DBRegion:
    Type: "String"
Resources:
  LambdaFunction:
    Type: "AWS::Serverless::Function"
    DeletionPolicy: Retain
    Properties:
      CodeUri: ./src
      FunctionName: !Sub "throwtrash-mobile-${Stage}"
      Handler: index.handler
      Role: !ImportValue  throwtrash-mobile-exec-role
      Runtime: nodejs12.x
      Timeout: 30
      Environment:
        Variables:
          DB_REGION: !Ref DBRegion
          RUNLEVEL: !Ref RunLevel
      Tags:
        Group: throwtrash
        Purpose: MobileBackend
      Events:
        Sync:
          Type: Api
          Properties:
            Path: "/sync"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.id:
                  Required: true
        PublishCode:
          Type: Api
          Properties:
            Path: "/publish_activation_code"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.id:
                  Required: true
        Register:
          Type: Api
          Properties:
            Path: "/register"
            Method: "POST"
            RestApiId: !Ref Api
        Update:
          Type: Api
          Properties:
            Path: "/update"
            Method: "POST"
            RestApiId: !Ref Api
        Activate:
          Type: Api
          Properties:
            Path: "/activate"
            Method: "GET"
            RestApiId: !Ref Api
            RequestParameters:
              - method.request.querystring.code:
                  Required: true
  Api:
    Type: "AWS::Serverless::Api"
    DeletionPolicy: Retain
    Properties:
      Name: !Sub "throwtrash-mobile-api-${Stage}"
      Tags:
        Group: throwtrash
        Purpose: MobileBackend
      StageName: !Ref Stage