name: Production Create Changeset

permissions:
  contents: read
  id-token: write

on:
  pull_request:
   types: [opened, reopened, synchronize]
   branches:
     - deploy

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      PR_NUMBER: ${{ steps.pr.outputs.PR_NUMBER }}
    steps:
      - uses: actions/checkout@v2
      - name: Get PR number
        id: pr
        run: echo "PR_NUMBER=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT
  backend-changeset:
    needs: ["get-pr-number"]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AWS Set up
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: build backend
        uses: ./.github/actions/backend/build
      - name: Set GCP Credentials
        run: |
          echo ${{ secrets.GCP_CREDENTIALS }} | base64 -d > backend/src/backend-dist/serviceAccountKey.json
      - name: Create Changeset for Backend DB
        run: |
          aws cloudformation create-change-set  --stack-name throwtrash-backend-db --template-body file://backend/cfn/db-template.yml --role-arn arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-cfn-role --capabilities CAPABILITY_NAMED_IAM --change-set-name "deploy-${{ needs.get-pr-number.outputs.PR_NUMBER }}" --region=${{ vars.AWS_DEFAULT_REGION }}
      - name: Create Changeset for Backend
        run: |
            # API/Lambdaのパッケージングとデプロイ
            aws cloudformation package --template-file backend/cfn/func-template.yml --output-template-file backend/cfn/package-template.yml --s3-bucket lambda-function-deployment-prod --s3-prefix throwtrashbackend

            aws cloudformation create-change-set --stack-name throwtrash-backend-${{ vars.BACK_STAGE }} --template-body file://backend/cfn/package-template.yml --change-set-name "deploy-${{ needs.get-pr-number.outputs.PR_NUMBER }}" --parameters ParameterKey=Stage,ParameterValue="${{ vars.BACK_STAGE }}" ParameterKey=FrontendStage,ParameterValue="${{ vars.FRONT_STAGE }}" ParameterKey=AlexaClientID,ParameterValue="${{ secrets.ALEXA_CLIENT_ID }}" ParameterKey=AlexaClientSecret,ParameterValue="${{ secrets.ALEXA_CLIENT_SECRET }}" ParameterKey=GoogleClientID,ParameterValue="${{ secrets.GOOGLE_CLIENT_ID }}" ParameterKey=GoogleClientSecret,ParameterValue="${{ secrets.GOOGLE_CLIENT_SECRET }}" ParameterKey=RunLevel,ParameterValue="${{ vars.RUNLEVEL }}"  ParameterKey=AlexaUserClientID,ParameterValue="${{ secrets.ALEXA_USER_CLIENT_ID }}" ParameterKey=AlexaUserSecret,ParameterValue="${{ secrets.ALEXA_USER_SECRET }}" ParameterKey=GoogleUserClientID,ParameterValue="${{ secrets.GOOGLE_USER_CLIENT_ID }}" ParameterKey=GoogleUserSecret,ParameterValue="${{ secrets.GOOGLE_USER_SECRET }}" ParameterKey=AlexaSkillID,ParameterValue="${{ secrets.ALEXA_SKILL_ID }}" ParameterKey=ApiGatewayOrigin,ParameterValue="${{ vars.BACKEND_API_GATEWAY_ORIGIN }}" --role-arn arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-cfn-role --capabilities CAPABILITY_NAMED_IAM
  mobile-backend-changeset:
    runs-on: ubuntu-latest
    needs: ["get-pr-number"]
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: AWS Set up
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - uses: ./.github/actions/mobile-backend/build
      - name: Create Changeset for Mobile Backend DB
        run: |
          aws cloudformation create-change-set --stack-name throwtrash-mobile-db --template-body file://api/db-template.yml --change-set-name "deploy-${{ needs.get-pr-number.outputs.PR_NUMBER }}" --role-arn arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-cfn-role --capabilities CAPABILITY_NAMED_IAM --region=${{ vars.AWS_DEFAULT_REGION }}
      - name: Create Changeset for Mobile Backend
        run: |
          # API/Lambdaのパッケージングとデプロイ
          aws cloudformation package --template-file api/func-template.yml --output-template-file api/package-template.yml --s3-bucket lambda-function-deployment-prod --s3-prefix throwtrashapi

          aws cloudformation create-change-set --stack-name throwtrash-mobile-${{ vars.MOBILE_API_STAGE }} --template-body file://api/package-template.yml --change-set-name "deploy-${{ env.PR_NUMBER }}" --parameters ParameterKey=RunLevel,ParameterValue="${{ vars.RUNLEVEL }}" ParameterKey=Stage,ParameterValue="${{ vars.MOBILE_API_STAGE }}" ParameterKey=SkillStage,ParameterValue="${{ vars.SKILL_STAGE }}" ParameterKey=AlexaSkillID,ParameterValue="${{ secrets.ALEXA_SKILL_ID }}" ParameterKey=AlexaClientID,ParameterValue="${{ secrets.ALEXA_CLIENT_ID }}" ParameterKey=AlexaClientSecret,ParameterValue="${{ secrets.ALEXA_CLIENT_SECRET }}" ParameterKey=AlexaUserClientID,ParameterValue="${{ secrets.ALEXA_USER_CLIENT_ID }}" ParameterKey=AuthorizationEndpoint,ParameterValue="${{ vars.BACKEND_API_ENDPOINT }}"/"${{ vars.BACK_STAGE }}" ParameterKey=BackendApiKey,ParameterValue="${{ secrets.BACKEND_API_KEY }}" --role-arn arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-cfn-role --capabilities CAPABILITY_NAMED_IAM